version: "3.1"
volumes:
  mysql-volume:
  ghost-volume:

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: mysql
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: blog-user
      MYSQL_PASSWORD: supersecret
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  ghost:
    build: ./ghost
    image: magicpages/ghost:latest
    container_name: ghost
    ports:
      - 2368:2368
    volumes:
      - ghost-volume:/var/lib/ghost
    restart: unless-stopped
    environment:
      url: http://localhost:2368
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: blog-user
      database__connection__password: supersecret
      database__connection__database: db
      database__connection__port: 3306
      port: 2368
      NODE_ENV: production
    depends_on:
      mysql:
        condition: service_healthy
    command: "node current/index.js"
