version: "3.1"
volumes:
  mysql-volume:
  ghost-volume:

services:
  mysql:
    image: mysql:8
    container_name: mysql
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: blog-user
      MYSQL_PASSWORD: supersecret
    ports:
      - 3306:3306

  ghost:
    build: ./ghost
    image: magicpages/ghost:latest
    container_name: ghost
    volumes:
      - ghost-volume:/var/lib/ghost/content
    restart: always
    ports:
      - 2368:2368
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: blog-user
      database__connection__password: supersecret
      database__connection__database: db
    depends_on:
      - mysql
    entrypoint: ["wait-for-it.sh", "mysql", "--", "docker-entrypoint.sh"]
    command: ["sh", "-c", "node current/index.js && ./prepare.sh"]
